-- Recurring invoice schedules.
--
-- A schedule captures a "template" Rechnung (any existing dokument row of
-- typ = 'rechnung') plus a cadence. When the scheduler runs, it clones the
-- template's structured fields into a fresh dokument with a new nummer +
-- datum, then advances next_generation_at.
--
-- Why a separate table instead of a column on dokumente?
--   * A schedule and its spawned invoices have different lifecycles (the
--     schedule can be paused/ended without affecting past deliveries).
--   * The "source" and "generated" rows are distinct dokumente; linking via
--     a table keeps that clean.
--
-- RLS mirrors dokumente — each user only sees their own schedules.

CREATE TABLE IF NOT EXISTS public.recurring_schedules (
  id                 uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id            uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  -- The source dokument whose positions/kunde/mwst/rabatt/notiz are cloned.
  -- We keep the FK even if the user deletes the template — ON DELETE SET NULL
  -- so past-generated invoices still show what schedule produced them, but
  -- a missing template pauses the schedule (enforced in the generator).
  template_dokument_id uuid REFERENCES public.dokumente(id) ON DELETE SET NULL,
  frequency          text NOT NULL CHECK (frequency IN ('weekly','monthly','quarterly','yearly')),
  next_generation_at date NOT NULL,
  last_generated_at  timestamptz,
  -- Optional end date; when next_generation_at passes this, the schedule
  -- auto-deactivates.
  end_date           date,
  active             boolean NOT NULL DEFAULT true,
  created_at         timestamptz NOT NULL DEFAULT now(),
  updated_at         timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_recurring_schedules_user_id
  ON public.recurring_schedules (user_id);

-- Generator lookup: find all due schedules quickly.
CREATE INDEX IF NOT EXISTS idx_recurring_schedules_due
  ON public.recurring_schedules (next_generation_at)
  WHERE active = true;

-- Track the provenance on the spawned document so the UI can show
-- "Generated by schedule X" and dedupe accidental double-runs.
ALTER TABLE public.dokumente
  ADD COLUMN IF NOT EXISTS recurring_schedule_id uuid
    REFERENCES public.recurring_schedules(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_dokumente_recurring_schedule_id
  ON public.dokumente (recurring_schedule_id)
  WHERE recurring_schedule_id IS NOT NULL;

-- RLS
ALTER TABLE public.recurring_schedules ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "recurring_schedules_owner_select" ON public.recurring_schedules;
CREATE POLICY "recurring_schedules_owner_select" ON public.recurring_schedules
  FOR SELECT USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "recurring_schedules_owner_insert" ON public.recurring_schedules;
CREATE POLICY "recurring_schedules_owner_insert" ON public.recurring_schedules
  FOR INSERT WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "recurring_schedules_owner_update" ON public.recurring_schedules;
CREATE POLICY "recurring_schedules_owner_update" ON public.recurring_schedules
  FOR UPDATE USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "recurring_schedules_owner_delete" ON public.recurring_schedules;
CREATE POLICY "recurring_schedules_owner_delete" ON public.recurring_schedules
  FOR DELETE USING (auth.uid() = user_id);
